//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlyHotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHI_TIET_DAT
    {
        public int CTD_ID { get; set; }
		[Required(ErrorMessage = "please fill in")]
		[Display(Name = "Check In day")]
		[DataType(DataType.Date)]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
		public System.DateTime CTD_NGAYDEN { get; set; }
		[Display(Name = "ID Type Room")]
		public int LP_IDLOAI { get; set; }
		[Display(Name = "ID Ticket")]
		public int PD_IDPHIEU { get; set; }
		[Display(Name = "Number of days")]
		[Required(ErrorMessage = "please fill in")]
		public int CTD_SONGAYO { get; set; }
		[Display(Name = "Number of rooms")]
		public int CTD_SOLUONGPHONG { get; set; }
    
        public virtual LOAI_PHONG LOAI_PHONG { get; set; }
        public virtual PHIEU_DAT PHIEU_DAT { get; set; }
    }
}
