//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlyHotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LOAI_PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAI_PHONG()
        {
            this.CHI_TIET_DAT = new HashSet<CHI_TIET_DAT>();
            this.PHONGs = new HashSet<PHONG>();
        }
		[Display(Name = "ID")]
		public int LP_IDLOAI { get; set; }
		[MaxLength(50, ErrorMessage = "Name of type up to 50 characters!")]
        [Display(Name = "Name")]

		public string LP_TENLOAI { get; set; }
		[Display(Name = "Price")]
		[DisplayFormat(DataFormatString = "{0:#,###.## VND}")]
		public decimal LP_GIA { get; set; }
		[Display(Name = "Quantity")]
		public Nullable<int> LP_SOLUONG { get; set; }
		[Display(Name = "Description")]
		[MaxLength(300, ErrorMessage = "Description up to 300 characters!")]
		public string LP_MOTA { get; set; }
		[Display(Name = "Image")]
		public string LP_HINHANH { get; set; }
		[Display(Name = "Maximum of people")]
		public Nullable<int> LP_SLNguoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_DAT> CHI_TIET_DAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
