//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlyHotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NGUOI_DUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOI_DUNG()
        {
            this.PHIEU_DAT = new HashSet<PHIEU_DAT>();
        }
    
        public int ND_IDNGUOIDUNG { get; set; }
        [Display(Name = "Full name")]
		public string ND_HOTEN { get; set; }
		[MaxLength(50, ErrorMessage = "Email up to 50 characters!")]
		[DataType(DataType.EmailAddress)]
		public string ND_EMAIL { get; set; }
		[Display(Name = "Username")]
		[Required(ErrorMessage = "Please fill in!")]
		[MaxLength(50, ErrorMessage = "Username up to 50 characters!")]
		public string ND_TAIKHOAN { get; set; }
		[Display(Name = "Password")]
		[Required(ErrorMessage = "please fill in")]
		[DataType(DataType.Password)]
		public string ND_MATKHAU { get; set; }
        public Nullable<int> ND_QUYENSD { get; set; }
        public string ND_AVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_DAT> PHIEU_DAT { get; set; }
    }
}
