//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlyHotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PHIEU_DAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_DAT()
        {
            this.CHI_TIET_DAT = new HashSet<CHI_TIET_DAT>();
        }
    
        public int PD_IDPHIEU { get; set; }
        public int ND_IDNGUOIDUNG { get; set; }
		[DataType(DataType.Date)]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
		public System.DateTime PD_NGAYDAT { get; set; }
		[DisplayFormat(DataFormatString = "{0:#,###.## VND}")]
		public Nullable<decimal> PD_TONGTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_DAT> CHI_TIET_DAT { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
    }
}
