//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlyHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public int P_IDPHONG { get; set; }
        public int LP_IDLOAI { get; set; }
        public bool P_TRANGTHAI { get; set; }
    
        public virtual LOAI_PHONG LOAI_PHONG { get; set; }
    }
}
